"""empty message

Revision ID: dd1b51385a89
Revises: 4374c72cf30a
Create Date: 2024-01-17 12:43:00.029803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1b51385a89'
down_revision = '4374c72cf30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_security_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=25), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=25), nullable=True),
    sa.Column('action_by', sa.String(length=25), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_security_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=25), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('todo_title', sa.String(length=150), nullable=True),
    sa.Column('todo_description', sa.Text(), nullable=True),
    sa.Column('todo_duedate', sa.DateTime(), nullable=True),
    sa.Column('todo_status', sa.Integer(), nullable=True),
    sa.Column('todo_user_id', sa.Integer(), nullable=True),
    sa.Column('action_by', sa.String(length=25), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_security_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=25), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('action_by', sa.String(length=25), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('todo_table', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('todo_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))

    op.drop_table('user_security_table')
    op.drop_table('todo_security_table')
    op.drop_table('role_security_table')
    # ### end Alembic commands ###
