FROM python:3 as dev

WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get -y install --no-install-recommends apt-utils zip unzip nano ncdu git vim gitg ssh 2>&1
RUN apt-get autoremove -y
RUN apt-get clean -y 
RUN rm -rf /var/lib/apt/lists/* 