version: '3'
services:
  web:
    container_name: SchoolTodoBackend
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    volumes:
      - ../:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
